CREATE TABLE configuracao_fechamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hora_execucao TIME NOT NULL
);

CREATE TABLE fechamentos_gerados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    formato VARCHAR(10) NOT NULL,
    nome_arquivo VARCHAR(255) NOT NULL,
    conteudo BYTEA NOT NULL,
    gerado_em TIMESTAMP NOT NULL
);
