CREATE TABLE operacoes_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operacao_id BIGINT NOT NULL REFERENCES operacoes(id),
    tipo VARCHAR(20) NOT NULL,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    criado_em TIMESTAMP NOT NULL,
    dados_anteriores TEXT
);

CREATE INDEX idx_operacoes_eventos_operacao_id ON operacoes_eventos(operacao_id);
