CREATE TABLE modelos_calculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    formula VARCHAR(255) NOT NULL
);

INSERT INTO modelos_calculo (nome, formula)
SELECT DISTINCT formula_comissao, formula_comissao FROM bancos WHERE formula_comissao IS NOT NULL;
