CREATE TABLE operacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_trade VARCHAR(20) NOT NULL UNIQUE,
    data DATE NOT NULL,
    codigo_banco VARCHAR(50),
    cliente_id BIGINT NOT NULL REFERENCES clientes(id),
    banco_id BIGINT NOT NULL REFERENCES bancos(id),
    cv VARCHAR(20) NOT NULL,
    pr_cr_vir VARCHAR(20) NOT NULL,
    moeda VARCHAR(10) NOT NULL,
    valor_me NUMERIC(18,2) NOT NULL,
    spot_asset NUMERIC(12,6) NOT NULL,
    nivelamento NUMERIC(12,6) NOT NULL,
    taxa_final NUMERIC(12,6) NOT NULL
);
